#479 Update to Python 3.11
gaganpreet/fastapi-starter pull request #707
Opened 2023-08-27 16:39 UTC by javi-aranda

This PR updates the Python version in a more effective way than the dependabot PR (https://github.com/gaganpreet/fastapi-starter/pull/481).

2023-08-28 09:15 UTC, gaganpreet requested changes
Thanks! Needs one change before this can be merged.

2023-08-28 09:15 UTC, gaganpreet commented on {{cookiecutter.project_slug}}/backend/poetry.lock
>  content-hash = "b9b023ab69303ecc173b452791fec2c66b70b59ab2a6344bd74611b56bd38a70"
The lockfile should be updated with a new content hash.

```bash
poetry lock --no-update
```

2023-08-28 13:33 UTC, javi-aranda commented
Thank you for your indications, following your command, now with Python 3.11, support for Tomli is no longer necessary as TOML parsing is included in the standard library ([PEP 680](https://peps.python.org/pep-0680/)) as well as the exceptiongroup package, which was a backport of the [`BaseExceptionGroup` and `ExceptionGroup` classes](https://docs.python.org/3/library/exceptions.html#exception-groups)

2023-09-04 08:46 UTC, gaganpreet approved these changes

2023-09-04 08:46 UTC, merged